version = 0.1

[default.deploy.parameters]
stack_name = "expense-tally"
resolve_s3 = true
s3_prefix = "expense-tally"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true

[default.build.parameters]
use_container = false
