name: 'Master branch maven release'
on:
  push:
    branches:
      - master
jobs:
  quality:
    name: 'Static code analysis'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          distribution: 'corretto'
          java-version: '18' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: 'SonarCloud Scan'
        run: mvn clean verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: 2euEqXYt
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ''
  release:
    name: 'Maven release'
    runs-on: 'ubuntu-20.04'
    # Skip commit made by maven-release
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          distribution: 'corretto'
          java-version: '18' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: 'Configure git commit'
        run: git config user.email "boyshawn@hotmail.com" && git config --global user.name "francis-pang"
      - name: 'Prepare release'
        run: mvn --batch-mode release:prepare -Dmaven.javadoc.skip=true -DskipTests
        env:
          MAVEN_GPG_PASSPHRASE: ''
      - name: 'Actual release'
        run: mvn --batch-mode release:perform -Dmaven.javadoc.skip=true -DskipTests
        env:
          MAVEN_USERNAME: 2euEqXYt
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ''

